---
- name: Template nginx configuration
  template: src="{{ item }}" dest="{{ render_path }}"
  loop_control:
    label: "{{ render_path }}"
  vars:
    template_dir: "{{ role_path }}/templates/nginx"
    render_path: "{{ nginx.prefix.config }}/{{ item|strip_prefix(template_dir + '/') }}"
  with_fileglob:
    - "{{ template_dir }}/*.htpasswd"
    - "{{ template_dir }}/http.d/*.conf"
  notify: Restart nginx
